version: '3.8'

services:
  # Database Services
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-bankingdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - banking-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-notificationdb}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - banking-network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - banking-network

  # Service Discovery
  eureka-server:
    image: ${DOCKER_REGISTRY:-banking}/service-registry:${TAG:-latest}
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - banking-network

  # Core Services
  user-service:
    image: ${DOCKER_REGISTRY:-banking}/user-service:${TAG:-latest}
    container_name: user-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=userdb
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here-should-be-at-least-256-bits-long}
      - SERVER_PORT=8085
    depends_on:
      - postgres
      - eureka-server
    networks:
      - banking-network

  account-service:
    image: ${DOCKER_REGISTRY:-banking}/account-service:${TAG:-latest}
    container_name: account-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=accountdb
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8082
    depends_on:
      - postgres
      - eureka-server
      - rabbitmq
    networks:
      - banking-network

  transaction-service:
    image: ${DOCKER_REGISTRY:-banking}/transaction-service:${TAG:-latest}
    container_name: transaction-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=transactiondb
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8083
    depends_on:
      - postgres
      - eureka-server
      - rabbitmq
    networks:
      - banking-network

  notification-service:
    image: ${DOCKER_REGISTRY:-banking}/notification-service:${TAG:-latest}
    container_name: notification-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=notificationdb
      - MONGO_USERNAME=${MONGO_USER:-admin}
      - MONGO_PASSWORD=${MONGO_PASSWORD:-admin}
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USERNAME=${EMAIL_USERNAME:-demo@example.com}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-demopassword}
      - SERVER_PORT=8084
    depends_on:
      - mongodb
      - eureka-server
      - rabbitmq
    networks:
      - banking-network

  auth-service:
    image: ${DOCKER_REGISTRY:-banking}/auth-service:${TAG:-latest}
    container_name: auth-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=authdb
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here-should-be-at-least-256-bits-long}
      - SERVER_PORT=8081
    depends_on:
      - postgres
      - eureka-server
    networks:
      - banking-network

  # API Gateway
  api-gateway:
    image: ${DOCKER_REGISTRY:-banking}/api-gateway:${TAG:-latest}
    container_name: api-gateway
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=demo
      - EUREKA_URL=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here-should-be-at-least-256-bits-long}
      - SERVER_PORT=8080
    ports:
      - "80:8080"
    depends_on:
      - eureka-server
      - user-service
      - account-service
      - transaction-service
      - notification-service
      - auth-service
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
