name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and Test User Service
      run: |
        cd services/user-service
        ./mvnw clean test
    
    - name: Build and Test Account Service
      run: |
        cd services/account-service
        ./mvnw clean test
    
    - name: Build and Test Transaction Service
      run: |
        cd services/transaction-service
        ./mvnw clean test
    
    - name: Build and Test Notification Service
      run: |
        cd services/notification-service
        ./mvnw clean test
    
    - name: Build and Test API Gateway
      run: |
        cd services/api-gateway
        ./mvnw clean test

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push User Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/user-service
        push: true
        tags: yourusername/banking-user-service:latest
    
    - name: Build and push Account Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/account-service
        push: true
        tags: yourusername/banking-account-service:latest
    
    - name: Build and push Transaction Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/transaction-service
        push: true
        tags: yourusername/banking-transaction-service:latest
    
    - name: Build and push Notification Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/notification-service
        push: true
        tags: yourusername/banking-notification-service:latest
    
    - name: Build and push API Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./services/api-gateway
        push: true
        tags: yourusername/banking-api-gateway:latest
